apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: INITIALS-carla # Change this to your initials
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
